"""empty message

Revision ID: d978aea9b912
Revises: 3f7e687ecb98
Create Date: 2023-12-28 00:36:39.777182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd978aea9b912'
down_revision = '3f7e687ecb98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=False))

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('created_date')

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_column('created_date')

    # ### end Alembic commands ###
